<?php
declare(strict_types=1);
$pageTitle='Сметы';
require_once __DIR__.'/includes/header.php';
if(!$pdo){echo '<div class="admin-card"><h2 class="admin-card-title">Нет подключения к БД</h2></div>';require_once __DIR__.'/includes/footer.php';exit;}
$pdo->exec("CREATE TABLE IF NOT EXISTS estimate_projects(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,client_name VARCHAR(255),city VARCHAR(150),status VARCHAR(30) NOT NULL DEFAULT 'draft',coefficient DECIMAL(10,4) NOT NULL DEFAULT 1.0000,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY status(status),KEY updated_at(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS estimate_categories(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,estimate_id INT UNSIGNED NOT NULL,name VARCHAR(255) NOT NULL,sort_order INT NOT NULL DEFAULT 0,KEY estimate_id(estimate_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS estimate_items(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id INT UNSIGNED NOT NULL,name VARCHAR(255) NOT NULL,quantity DECIMAL(14,3) NOT NULL DEFAULT 1,unit VARCHAR(30) NOT NULL DEFAULT 'шт',price DECIMAL(14,2) NOT NULL DEFAULT 0,sort_order INT NOT NULL DEFAULT 0,KEY category_id(category_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$a=$_POST['action']??'';
if($a==='create'){$q=$pdo->prepare("INSERT INTO estimate_projects(title,client_name,city) VALUES(?,?,?)");$q->execute([trim($_POST['title']??'Новая смета'),trim($_POST['client_name']??''),trim($_POST['city']??'')]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare("INSERT INTO estimate_categories(estimate_id,name,sort_order) VALUES(?,?,1)");$q->execute([$id,'Материалы и работы']);redirect('estimate-edit.php?id='.$id);}
if($a==='delete'){$id=(int)($_POST['id']??0);$pdo->beginTransaction();try{$q=$pdo->prepare("DELETE ei FROM estimate_items ei JOIN estimate_categories ec ON ec.id=ei.category_id WHERE ec.estimate_id=?");$q->execute([$id]);$q=$pdo->prepare("DELETE FROM estimate_categories WHERE estimate_id=?");$q->execute([$id]);$q=$pdo->prepare("DELETE FROM estimate_projects WHERE id=?");$q->execute([$id]);$pdo->commit();}catch(Throwable $e){$pdo->rollBack();throw $e;}redirect('estimates.php');}}
$rows=$pdo->query("SELECT ep.*,COALESCE((SELECT SUM(i.quantity*i.price) FROM estimate_items i JOIN estimate_categories c ON c.id=i.category_id WHERE c.estimate_id=ep.id),0) direct_total,COALESCE((SELECT COUNT(*) FROM estimate_items i JOIN estimate_categories c ON c.id=i.category_id WHERE c.estimate_id=ep.id),0) item_count,COALESCE((SELECT COUNT(*) FROM estimate_categories c WHERE c.estimate_id=ep.id),0) category_count FROM estimate_projects ep ORDER BY ep.updated_at DESC,ep.id DESC")->fetchAll();
function eg(float $d,float $c):float{$b=$d*$c;return $b+$b*.15+$b*.08+($b+$b*.15+$b*.08)*.2;}
?>
<div class="estimate-admin-page"><div class="admin-page-head"><div><div class="estimate-admin-eyebrow">CONCEPT / СМЕТЫ</div><h2 class="estimate-admin-title">Сметные проекты</h2><p class="estimate-admin-lede">Отдельные проекты только для расчёта стоимости — по логике Smetogram.</p></div><button class="admin-btn admin-btn--primary" data-bs-toggle="modal" data-bs-target="#newEstimate"><i class="bi bi-plus-lg"></i> Новая смета</button></div>
<?php if($rows):?><div class="estimate-project-grid"><?php foreach($rows as $e):$total=eg((float)$e['direct_total'],(float)$e['coefficient']);?><article class="estimate-project-card"><div class="estimate-project-card-top"><span class="estimate-project-status"><i></i><?=h(['draft'=>'Черновик','in_progress'=>'В работе','review'=>'На согласовании','completed'=>'Завершена','archived'=>'Архив'][$e['status']]??$e['status'])?></span><span class="estimate-project-id">#<?=$e['id']?></span></div><a class="estimate-project-card-title" href="estimate-edit.php?id=<?=$e['id']?>"><?=h($e['title'])?></a><div class="estimate-project-meta"><span><i class="bi bi-person"></i><?=h($e['client_name']?:'Заказчик не указан')?></span><span><i class="bi bi-geo-alt"></i><?=h($e['city']?:'Город не указан')?></span></div><div class="estimate-project-stats"><div><span>Разделы</span><b><?=$e['category_count']?></b></div><div><span>Позиций</span><b><?=$e['item_count']?></b></div><div><span>Коэффициент</span><b>× <?=number_format((float)$e['coefficient'],3,',','')?></b></div></div><div class="estimate-project-total"><span>Итого</span><strong><?=number_format($total,2,',',' ')?> ₽</strong></div><div class="estimate-project-actions"><a href="estimate-edit.php?id=<?=$e['id']?>" class="admin-btn admin-btn--primary"><i class="bi bi-calculator"></i> Открыть смету</a><form method="post" onsubmit="return confirm('Удалить смету и все позиции?')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$e['id']?>"><button class="icon-btn icon-btn--danger"><i class="bi bi-trash"></i></button></form></div></article><?php endforeach;?></div><?php else:?><div class="estimate-admin-empty admin-card"><div class="estimate-admin-empty-icon"><i class="bi bi-calculator"></i></div><h3>Смет пока нет</h3><p>Создайте отдельный проект и собирайте полноценную смету.</p><button class="admin-btn admin-btn--primary" data-bs-toggle="modal" data-bs-target="#newEstimate"><i class="bi bi-plus-lg"></i> Создать первую смету</button></div><?php endif;?></div>
<div class="modal fade" id="newEstimate" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title">Новый проект сметы</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><?=csrf_field()?><input type="hidden" name="action" value="create"><div class="estimate-form-grid"><label><span>Название сметы *</span><input name="title" required placeholder="Кухня — квартира на Курортном"></label><label><span>Заказчик</span><input name="client_name"></label><label><span>Город</span><input name="city" value="Сочи"></label></div></div><div class="modal-footer"><button type="button" class="admin-btn admin-btn--outline" data-bs-dismiss="modal">Отмена</button><button class="admin-btn admin-btn--primary">Создать смету</button></div></form></div></div></div>
<style>
.estimate-admin-title{margin:5px 0 6px;font-size:30px;color:var(--ink)}.estimate-admin-eyebrow{font-size:10px;letter-spacing:.16em;color:var(--gold-2);font-weight:800}.estimate-admin-lede{margin:0;color:var(--muted);font-size:13px}.estimate-project-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.estimate-project-card{background:var(--bg-2);border:1px solid var(--line);border-radius:var(--r);padding:20px;transition:.2s}.estimate-project-card:hover{transform:translateY(-2px);border-color:var(--line-2)}.estimate-project-card-top,.estimate-project-total,.estimate-project-actions{display:flex;justify-content:space-between;align-items:center;gap:10px}.estimate-project-status{font-size:10px;text-transform:uppercase;color:var(--muted);font-weight:700}.estimate-project-status i{display:inline-block;width:6px;height:6px;border-radius:50%;background:var(--gold);margin-right:6px}.estimate-project-id{font:10px monospace;color:var(--muted-2)}.estimate-project-card-title{display:block;margin:22px 0 14px;color:var(--ink);font-size:18px;font-weight:700;text-decoration:none}.estimate-project-card-title:hover{color:var(--gold-2)}.estimate-project-meta{display:grid;gap:7px;color:var(--muted);font-size:11px}.estimate-project-meta span{display:flex;gap:7px}.estimate-project-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:20px 0;padding:13px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.estimate-project-stats span,.estimate-project-stats b{display:block}.estimate-project-stats span{font-size:9px;color:var(--muted-2);text-transform:uppercase}.estimate-project-stats b{margin-top:5px;color:var(--ink)}.estimate-project-total{margin-bottom:18px}.estimate-project-total span{font-size:11px;color:var(--muted)}.estimate-project-total strong{font:700 19px monospace;color:var(--gold-2)}.estimate-project-actions .admin-btn{flex:1}.estimate-admin-empty{text-align:center;padding:70px 30px}.estimate-admin-empty-icon{width:60px;height:60px;margin:0 auto 16px;border-radius:18px;background:rgba(199,157,109,.12);display:grid;place-items:center;color:var(--gold-2);font-size:25px}.estimate-admin-empty h3{color:var(--ink)}.estimate-admin-empty p{color:var(--muted);font-size:13px}.estimate-form-grid{display:grid;gap:15px}.estimate-form-grid label{display:grid;gap:7px}.estimate-form-grid label span{font-size:10px;text-transform:uppercase;color:var(--muted);font-weight:700}.estimate-form-grid input{width:100%;background:var(--bg-3);border:1px solid var(--line);border-radius:var(--r-2);padding:12px;color:var(--ink)}@media(max-width:1100px){.estimate-project-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.estimate-project-grid{grid-template-columns:1fr}.estimate-admin-title{font-size:24px}}
</style>
<?php require_once __DIR__.'/includes/footer.php';